joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeate_rate: 20

teleop_node:
  ros__parameters:
    axis_linear:
      x: 3 #number given by /joy topic
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 2.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 1.0

    enable_turbo_button: 5

    require_enable_button: false

    
    


